name: fitcrew
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.8.0
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  health: ^12.0.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mockito: ^5.4.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/png/color_with_background.png
    - assets/png/color_no_background.png
    - assets/png/black_no_background.png
    - assets/png/padded_logo.png
    - assets/png/white_no_background.png